#!/bin/bash
sudo -i
yum update -y
yum install epel-release -y
yum install -y net-tools vim tree wget curl traceroute
dnf -y install https://www.elrepo.org/elrepo-release-8.el8.elrepo.noarch.rpm
rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
dnf --disablerepo="*" --enablerepo="elrepo-kernel" list available | grep kernel-ml
dnf -y --enablerepo=elrepo-kernel install kernel-ml
dnf -y --enablerepo=elrepo-kernel install kernel-ml-{devel,headers}
yum update -y
sudo reboot
